name: Cache
on: push
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # 1. ソースコードのチェックアウト
      - uses: actions/cache@v4 #  キャッシュの復元と保存 2. キャッシュアクションを呼び出し、ダミーファイルをキャッシュから復元
        with:
          key: test-${{ runner.os }}-${{ github.sha }} # キャッシュキー
          path: ${{ github.workspace }}/dummy # キャッシュ対象のパス
          restore-keys: | # リストアキー
            test-${{ runner.os }}-
      - run: | # 3. ダミーファイルがない場合はダミーファイルを生成
          if [[ -f "${GITHUB_WORKSPACE}/dummy" ]]; then exit 0; fi
          dd if=/dev/urandom of="${GITHUB_WORKSPACE}/dummy" bs=1M count=10
          sleep 30
      - run: ls -ls "${GITHUB_WORKSPACE}/dummy" # 4. ダミーファイルの確認
