name: Conditions
on: push
jobs:
  skip-or-run:
    runs-on: ubuntu-latest
    env:
      RUN_ID: ${{ github.run_id }}
    steps:
      - run: echo "${RUN_ID}"
      - run: echo "Hello"
        if: ${{ contains(env.RUN_ID, '1') }}
